package com.example.colorpaper.data.model

import androidx.room.*

@Entity(tableName = "folders")
data class FolderEntity(
    @PrimaryKey(autoGenerate = true) @ColumnInfo(name = "folder_id") val folderId: Int = 0,
    @ColumnInfo(name = "user_id") val userId: Int,
    @ColumnInfo(name = "folder_name") val folderName: String,
    @ColumnInfo(name = "is_auto_generated") val isAutoGenerated: Boolean = false
)