package com.example.colorpaper.data.repository

import com.example.colorpaper.data.local.FlashcardDao
import com.example.colorpaper.data.model.FolderEntity
import com.example.colorpaper.data.model.WordEntity
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withContext

class FlashcardRepository(private val flashcardDao: FlashcardDao) {

    private val firestore = FirebaseFirestore.getInstance()

    // 1. 특정 유저의 단어장 세트 목록 조회 (로컬 DB)
    suspend fun getMyFolders(userId: String): List<FolderEntity> = withContext(Dispatchers.IO) {
        flashcardDao.getAllSetsByUserId(userId)
    }

    // 2. 전체 공개 단어장 목록 조회 (로컬 DB)
    suspend fun getSharedFolders(): List<FolderEntity> = withContext(Dispatchers.IO) {
        flashcardDao.getSharedFlashcardSets()
    }

    // 3. 단어장 세트 내 단어 카드 목록 조회 (로컬 DB)
    suspend fun getWordsByFolderId(folderId: Int): List<WordEntity> = withContext(Dispatchers.IO) {
        flashcardDao.getItemsBySetId(folderId.toLong())
    }

    // 4. 단어장 생성 (로컬 DB 저장 + 백엔드 Firestore 동기화)
    suspend fun createFolder(folder: FolderEntity): Long = withContext(Dispatchers.IO) {
        val insertedId = flashcardDao.insertFolder(folder)

        // 공개 단어장인 경우 백엔드(Firestore) 서버에도 업로드
        if (folder.visibility == "전체공개") {
            try {
                val folderData = hashMapOf(
                    "folderId" to insertedId,
                    "userId" to folder.userId,
                    "folderName" to folder.folderName,
                    "isAutoGenerated" to folder.isAutoGenerated,
                    "visibility" to folder.visibility
                )
                firestore.collection("flashcard_folders")
                    .document(insertedId.toString())
                    .set(folderData)
                    .await()
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        insertedId
    }

    // 5. 단어 목록 일괄 추가 (로컬 DB)
    suspend fun insertWords(words: List<WordEntity>) = withContext(Dispatchers.IO) {
        flashcardDao.insertAllItems(words)
    }

    // 6. 단어 카드 정보/암기상태 업데이트
    suspend fun updateWord(word: WordEntity) = withContext(Dispatchers.IO) {
        flashcardDao.updateWord(word)
    }

    // 7. 단어장 삭제 (로컬 DB + 백엔드 삭제)
    suspend fun deleteFolder(folder: FolderEntity) = withContext(Dispatchers.IO) {
        flashcardDao.deleteSet(folder)
        try {
            firestore.collection("flashcard_folders")
                .document(folder.folderId.toString())
                .delete()
                .await()
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}