package com.example.colorpaper.ui.flashcard

import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.fragment.app.Fragment
import androidx.lifecycle.lifecycleScope
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.colorpaper.R
import com.example.colorpaper.data.local.AppDatabase
import com.example.colorpaper.data.model.FolderEntity
import com.example.colorpaper.databinding.FragmentFlashcardBinding
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withContext

class FlashcardFragment : Fragment() {

    private var _binding: FragmentFlashcardBinding? = null
    private val binding get() = _binding!!

    private lateinit var adapter: FlashcardSetAdapter
    private val auth = FirebaseAuth.getInstance()
    private val firestore = FirebaseFirestore.getInstance()

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentFlashcardBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val safeContext = context?.applicationContext ?: return

        adapter = FlashcardSetAdapter(
            emptyList(),
            onStartClick = { selectedSet ->
                val bundle = Bundle().apply {
                    putInt("SET_ID", selectedSet.folderId)
                    putString("SET_TITLE", selectedSet.folderName)
                }
                val studyFragment = FlashcardStudyFragment().apply { arguments = bundle }
                parentFragmentManager.beginTransaction()
                    .replace(R.id.fragment_container, studyFragment)
                    .addToBackStack(null)
                    .commit()
            },
            onItemLongClick = { selectedSet ->
                showDeleteDialog(selectedSet)
            }
        )

        binding.rvFlashcardSets.apply {
            this.adapter = this@FlashcardFragment.adapter
            this.layoutManager = LinearLayoutManager(safeContext)
            this.setHasFixedSize(true)
        }

        binding.btnCreateSet.setOnClickListener {
            parentFragmentManager.beginTransaction()
                .replace(R.id.fragment_container, FlashcardCreateFragment())
                .addToBackStack(null)
                .commit()
        }
    }

    override fun onResume() {
        super.onResume()
        loadFlashcardSets()
    }

    // 🌟 Firebase Firestore 연동 + Local Room DB 동기화 불러오기 (await 적용)
    private fun loadFlashcardSets() {
        val safeContext = context?.applicationContext ?: return
        val currentUserId = auth.currentUser?.uid

        if (currentUserId.isNullOrEmpty()) {
            // 미로그인 상태 시 로컬 DB 조회 Fallback
            loadLocalFlashcardSets()
            return
        }

        viewLifecycleOwner.lifecycleScope.launch {
            try {
                // 1. IO 스레드에서 Firestore 및 Room DB 동기화 실행
                val allSets = withContext(Dispatchers.IO) {
                    val dao = AppDatabase.getDatabase(safeContext).flashcardDao()

                    try {
                        val snapshot = firestore.collection("folders")
                            .whereEqualTo("userId", currentUserId)
                            .get()
                            .await()

                        val firestoreSets = snapshot.documents.mapNotNull { doc ->
                            val folderName = doc.getString("folderName") ?: doc.getString("folder_name") ?: ""
                            val visibility = doc.getString("visibility") ?: "전체공개"
                            val isAuto = doc.getBoolean("isAutoGenerated") ?: doc.getBoolean("is_auto_generated") ?: false
                            val rawFolderId = doc.getLong("folderId")?.toInt() ?: doc.id.hashCode()

                            FolderEntity(
                                folderId = rawFolderId,
                                userId = currentUserId,
                                folderName = folderName,
                                isAutoGenerated = isAuto,
                                visibility = visibility
                            )
                        }

                        // Firestore 데이터를 로컬 Room DB에 저장/동기화
                        firestoreSets.forEach { dao.insertFolder(it) }

                        val localData = dao.getAllSetsByUserId(currentUserId)
                        if (localData.isNotEmpty()) localData else firestoreSets

                    } catch (e: Exception) {
                        if (e is CancellationException) throw e
                        Log.e("FlashcardFragment", "Firestore 동기화 실패 -> 로컬 DB 조회", e)
                        // 통신 실패 시 로컬 DB 데이터 가져오기
                        dao.getAllSetsByUserId(currentUserId)
                    }
                }

                // 2. 화면 분리 여부 체크 후 안전하게 UI 반영
                if (!isAdded || _binding == null) return@launch
                updateUi(allSets)

            } catch (e: Exception) {
                if (e !is CancellationException) {
                    Log.e("FlashcardFragment", "loadFlashcardSets 에러", e)
                }
            }
        }
    }

    private fun loadLocalFlashcardSets() {
        val safeContext = context?.applicationContext ?: return

        viewLifecycleOwner.lifecycleScope.launch {
            val dao = AppDatabase.getDatabase(safeContext).flashcardDao()
            val currentUserId = auth.currentUser?.uid ?: ""

            val sets = withContext(Dispatchers.IO) {
                if (currentUserId.isNotEmpty()) {
                    dao.getAllSetsByUserId(currentUserId)
                } else {
                    dao.getAllSets()
                }
            }

            if (!isAdded || _binding == null) return@launch
            updateUi(sets)
        }
    }

    private fun updateUi(sets: List<FolderEntity>) {
        val currentBinding = _binding ?: return
        if (sets.isEmpty()) {
            currentBinding.tvEmptyHint.visibility = View.VISIBLE
            currentBinding.rvFlashcardSets.visibility = View.GONE
        } else {
            currentBinding.tvEmptyHint.visibility = View.GONE
            currentBinding.rvFlashcardSets.visibility = View.VISIBLE
            adapter.updateData(sets)
        }
    }

    // 🌟 파이어베이스 & 로컬 DB 양쪽 모두에서 삭제 수행 (순차적 비동기 처리)
    private fun showDeleteDialog(flashcardSet: FolderEntity) {
        val dialogContext = context ?: return
        val safeAppContext = dialogContext.applicationContext

        AlertDialog.Builder(dialogContext)
            .setTitle("플립카드 삭제")
            .setMessage("${flashcardSet.folderName} 플립카드를 정말 삭제하시겠습니까?\n내부 카드들도 함께 삭제됩니다.")
            .setPositiveButton("삭제") { _, _ ->
                val currentUserId = auth.currentUser?.uid ?: ""

                viewLifecycleOwner.lifecycleScope.launch {
                    try {
                        withContext(Dispatchers.IO) {
                            // 1. Firebase Firestore 문서 삭제
                            if (currentUserId.isNotEmpty()) {
                                val querySnapshot = firestore.collection("folders")
                                    .whereEqualTo("userId", currentUserId)
                                    .whereEqualTo("folderName", flashcardSet.folderName)
                                    .get()
                                    .await()

                                for (doc in querySnapshot.documents) {
                                    doc.reference.delete().await()
                                }
                            }

                            // 2. Room Local DB 삭제
                            val dao = AppDatabase.getDatabase(safeAppContext).flashcardDao()
                            dao.deleteSet(flashcardSet)
                        }

                        // 3. UI 상태 및 Toast 갱신
                        if (!isAdded || _binding == null) return@launch
                        Toast.makeText(safeAppContext, "삭제되었습니다.", Toast.LENGTH_SHORT).show()
                        loadFlashcardSets()

                    } catch (e: Exception) {
                        if (e !is CancellationException) {
                            Log.e("FlashcardFragment", "플립카드 삭제 처리 중 오류", e)
                        }
                    }
                }
            }
            .setNegativeButton("취소", null)
            .show()
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}